---
# This file configures GitHub actions
# --- specifies that it is a yml file
name: Checks 

on: [push]  # auto runs on push

jobs: 
  test-lint:  # job id
    name: Test and Lint  # interface name for job
    runs-on: ubuntu-20.04  # what test will be run on, docker already installed on this specific os
    steps:
      - name: Login to Docker Hub  # name of step
        uses: docker/login-action@v1  # use premade action in github repo
        with:  # parameters passed into action
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout  # runs if prev was successful, sequential
        uses: actions/checkout@v2  # 'checkouts' code so it can be accessed
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"  # runs unit test for code
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"  # runs linting
